### ISSUE TITLE
v4 support

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox-bindep#25]
v4 is getting ready and we'd like to make sure this plugin is supported from day 1, we're collecting feature gaps for this under https://github.com/tox-dev/tox/issues/1974. Would be great if you could join our development chat under https://discord.gg/tox so we can assist with this. If you do so please drop in a line in the `#plugin` chat with the name of the repository you maintain. Thanks!

**Comment by ssbarnea** [comment]
This functionality is now covered by https://github.com/tox-dev/tox-extra - I am archiving tox-bindep plugin.
